### PR TITLE
enable heatmap

### PR DESCRIPTION
**Pull request by Ovilia**

### CODE REVIEW

**Comment by suxuekun** [comment]
pulled and heatmap examples not working

**Comment by Ovilia** [comment]
@suxuekun Before next release, you need to set `developMode` to be `false` in Line 132, and add `'echarts/chart/heatmap'` in the last require in `doc/asset/js/echartsExample.js` and then check the examples again.

**Comment by suxuekun** [comment]
all examples down after adding the require 
    require(
        [
            'echarts',
            'theme/' + hash.replace('-en', ''),
            'echarts/chart/line',
            'echarts/chart/bar',
            'echarts/chart/scatter',
            'echarts/chart/k',
            'echarts/chart/pie',
            'echarts/chart/radar',
            'echarts/chart/force',
            'echarts/chart/chord',
            'echarts/chart/gauge',
            'echarts/chart/funnel',
            'echarts/chart/eventRiver',
            'echarts/chart/venn',
            'echarts/chart/treemap',
            'echarts/chart/tree',
            'echarts/chart/wordCloud',
            needMap() ? 'echarts/chart/map' : 'echarts',
            'echarts/chart/heatmap'
        ],
        requireCallback
    );

**Comment by Ovilia** [comment]
@suxuekun Sorry.. `developMode` should be set to be `true`.

**Pull request merged**
