### PR TITLE
Fix bar overflow issues #4862 Bug fix

### PR DESCRIPTION
**Pull request by c-okelly**
I would like to propose the following pull request in reference to issue fixing #4862
针对问题 #4862， 我想提供一个合并请求。

**Summary**
**概述**

Rescale relevant base axis (of time and interval) to account for overflow of bars beyond chart.
伸缩相关的坐标轴（时间和区间）来解决长条溢出图表的问题

**Overview of changes**
**修改简述**

Two files edited.
共修改了两个文件

AxisHelper.js => has additional function to rescale axis
AxisHelper.js => 添加了伸缩坐标的函数

barGrid.js => export calBarWidthAndOffset
barGrid.js => 添加了calBarWidthAndOffset

**Proposed changes**
**所做的修改**

1. If axis is (time or interval) and has more then one bar and is a base axis
=> Recalculate axis min / max to account for bar overflow
如果坐标轴是时间或区间，并且有多个长条，并且次坐标为基本坐标，
那么伸缩坐标的最小最大值来解决长条溢出问题
2. Calculate physical length of current axis
计算现有坐标的物理长度
3. Calculate placement of bars on current axis
计算长条在坐标上的位置
4. Use current baseAxis to select bars on relevant axis
用当前的基本坐标来选择在相应坐标上的长条
=> If no bars on current axis return current max / min
如果，没有长条，那么返回当前的最大最小值
5. Rescale axis to account for overflow on each side of the chart
伸缩坐标来解决溢出问题
6. Return new axis min / max
返回新的最大最小值

**Test**
I have updated to include a test in file bar-overflow-time-plot.html

**Extra**
This issue also occurs with candlestick plotting on ordinal axis.
This could also be corrected with a similar function.
This can be seen in https://ecomfe.github.io/echarts-examples/public/editor.html?c=candlestick-sh

### CODE REVIEW

**Comment by c-okelly** [comment]
@pissang Is there any changes / refactoring you would like done? As would be very keen to see this integrated into the main echarts repo! 

Thanks,

Conor

**Comment by roblav96** [comment]
Please merge, this is fantastic! @c-okelly @hanleyt @graysr89

**Comment by pissang** [comment]
Hi @c-okelly, Sorry for the late reply.

This is really an ancient issue from the very beginning. Thanks your affort for solving this issue!! The solution is neat. 

Some suggestions:
```js
model.ecModel._componentsMap._ec_series
```
It is not suggested to access the private properties which start with '_'. Instead you can use
```js
model.ecModel.getSeries()
```

And there is no need to import the whole `barGrid` module. Instead you can only import the `calBarWidthAndOffset` method and let rollup do the tree shaking.
```js
import { calBarWidthAndOffset } from '../layout/barGrid'
```

Thanks again!

**Comment by c-okelly** [comment]
Hi @pissang , 

Thank you very much for getting back to me and thank you for the clear feedback on changes.

I have updated the pull request to include all the changes that you have requested. 

1. Replace private property access with getters
2. Import single function from barGrid instead of whole module

Please let me know if you would like anything else changed!

Thanks,

Conor

**Comment by c-okelly** [comment]
Hi @pissang @100pah,

I have just noticed that the build script build.js throws an assertion error on barGrid as I am both exporting a function and doing a default export.

[transform]  /Users/conorokelly/Desktop/echarts/src/layout/barGrid.js ...
assert.js:41
  throw new errors.AssertionError({
  ^

AssertionError [ERR_ASSERTION]: Forbiden that both export default and others.

I am currently working on a solution.

Apologies,

Conor

**Pull request merged**
